"""Ollama HTTP client wrapper.

Provides a clean, type-safe interface to a local Ollama inference server.
This client will be reused across the LLM, RAG, and Agent layers.
"""

import json
from typing import Iterator

import requests

from app.core.config import settings
from app.llm.errors import LLMClientError


class OllamaError(LLMClientError):
    """Raised when communication with the Ollama server fails."""


class OllamaClient:
    """Lightweight wrapper around the Ollama REST API."""

    def __init__(
        self,
        host: str | None = None,
        model: str | None = None,
        timeout: int | None = None,
    ) -> None:
        self.host = (host or settings.ollama_host).rstrip("/")
        self.model = model or settings.ollama_model
        self.timeout = timeout or settings.request_timeout

    def health_check(self) -> bool:
        """Check whether the Ollama server is reachable.

        Returns:
            True if the server responds successfully, False otherwise.
        """
        try:
            response = requests.get(f"{self.host}/api/tags", timeout=5)
            return response.status_code == 200
        except requests.RequestException:
            return False

    def generate(self, prompt: str, options: dict | None = None) -> str:
        """Send a prompt to the model and return the full response.

        Args:
            prompt: The user prompt to send to the model.
            options: Ollama sampling options (e.g. ``{"temperature": 0,
                "num_predict": 5}``); ``None`` keeps the server defaults.

        Returns:
            The model's full text response.

        Raises:
            OllamaError: If the request fails or returns a non-200 status.
        """
        payload: dict = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
        }
        if options:
            payload["options"] = options
        try:
            response = requests.post(
                f"{self.host}/api/generate",
                json=payload,
                timeout=self.timeout,
            )
            response.raise_for_status()
            return response.json()["response"]
        except requests.RequestException as exc:
            raise OllamaError(f"Failed to generate response: {exc}") from exc

    def generate_stream(self, prompt: str) -> Iterator[str]:
        """Stream the model's response token-by-token.

        Args:
            prompt: The user prompt to send to the model.

        Yields:
            Individual text chunks as they are generated by the model.

        Raises:
            OllamaError: If the request fails.
        """
        try:
            with requests.post(
                f"{self.host}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": True,
                },
                timeout=self.timeout,
                stream=True,
            ) as response:
                response.raise_for_status()
                for line in response.iter_lines():
                    if not line:
                        continue
                    chunk = json.loads(line)
                    if "response" in chunk:
                        yield chunk["response"]
                    if chunk.get("done"):
                        break
        except requests.RequestException as exc:
            raise OllamaError(f"Failed to stream response: {exc}") from exc
